name: verify

on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Prettier
        id: prettier-run
        run: bun prettier

      - name: Run Eslint
        id: eslint-run
        run: bun eslint

      - name: Run Stylelint
        id: stylelint-run
        run: bun stylelint

      - name: Run Tsc
        id: tsc-run
        run: bun tsc

      - name: Run Test Coverage
        id: test-coverage-run
        run: bun test:coverage
